<?php
	/*
		Avatar CSS version 2.0
		Now with Multiple Avatars!
		(c)2013 Psychatica Entertainment Group / Michael Becker
	*/
	
	global $RootPath;
	$RootPath = dirname(__FILE__) . "/../";
	
	use WebFX\System;
	
	use PhoenixSNS\Objects\AvatarBase;
	
	require("WebFX/WebFX.inc.php");
	
	header("Content-Type: text/css");
	
	$bases = AvatarBase::Get();
	echo("/* generated by PhoenixSNS 1.2, do not modify. (c)2013 Psychatica Entertainment Group / Michael Becker */ ");
	
	function RenderSliceRecursive($slice)
	{
		echo("div.Avatar" . $slice->Base->ID . " div." . $slice->Name . "\r\n");
		echo("{\r\n");
		echo("\tbackground-image: url('" . System::ExpandRelativePath("~/images/avatar/bases/" . $slice->Base->ID . "/1/slices/" . $slice->Name . ".png');\r\n"));
		echo("\tposition: absolute;\r\n");
		echo("\tleft: " . $slice->Left . "px;\r\n");
		echo("\ttop: " . $slice->Top . "px;\r\n");
		echo("\twidth: " . $slice->Width . "px;\r\n");
		echo("\theight: " . $slice->Height . "px;\r\n");
		echo("\ttransform-origin: " . $slice->OriginLeft . "px " . $slice->OriginTop . "px;\r\n");
		echo("}\r\n");
		
		$slices = $slice->GetSlices();
		foreach ($slices as $slice1)
		{
			RenderSliceRecursive($slice1);
		}
	}
	
	foreach ($bases as $base)
	{
		$slices = $base->GetSlices();
		echo("/* begin base " . $base->ID . " */\r\n");
		
		echo("div.Avatar.Avatar" . $base->ID . " div.error\r\n");
		echo("{\r\n");
		echo("\tbackground-image: url('" . System::ExpandRelativePath("~/images/avatar/bases/" . $base->ID . "/1/loading/error.png") . "');\r\n");
		echo("\twidth: " . $base->Width . "px;\r\n");
		echo("\theight: " . $base->Height . "px;\r\n");
		echo("\tcursor: help;\r\n");
		echo("}\r\n");
		
		echo("div.Avatar.Avatar" . $base->ID . " div.loading\r\n");
		echo("{\r\n");
		echo("\tdisplay: none;\r\n");
		echo("\tbackground-image: url('" . System::ExpandRelativePath("~/images/avatar/bases/" . $base->ID . "/1/loading/outline.png") . "');\r\n");
		echo("\twidth: " . $base->Width . "px;\r\n");
		echo("\theight: " . $base->Height . "px;\r\n");
		echo("}\r\n");
		
		echo("div.Avatar.Avatar" . $base->ID . " div.loading img.fill\r\n");
		echo("{\r\n");
		echo("\twidth: " . $base->Width . "px;\r\n");
		echo("\theight: " . $base->Height . "px;\r\n");
		echo("}\r\n");
		
		foreach ($slices as $slice)
		{
			RenderSliceRecursive($slice);
		}
		echo("/* end base " . $base->ID . " */\r\n");
	}
?>